version: 2


steps: &steps
  steps:
#    - restore_cache:
#        keys:
#          - cache-{{ .Environment.CIRCLE_JOB }}
    - checkout
#    - run:
#        name: Install package dependencies env
#        command: sudo apt-get update && sudo apt install jags && sudo apt-get install -y r-cran-rgl
#    - run:
#        name: extralearners
#        command: R -e "remotes::install_github('mlr-org/mlr3extralearners')"
    - run:
        name: Install Biobase
        command: R -e "install.packages('BiocManager'); BiocManager::install('Biobase'); BiocManager::install('globaltest')"
    - run:
        name: Install package dependencies
        command: R -e "devtools::install_deps(dep = TRUE)"
    - run:
        name: Install package dependencies manually
        command: Rscript -e "install.packages(c( 'fmsb', 'kableExtra',  'nmfbin',  'glasso',  'FRESA.CAD', 'gaston', 'NMF','wesanderson','ggthemes','ggstatsplot','ciTools'))"
    - run:
        no_output_timeout: 30m
        name: Build package
        command: R CMD build .
    - run:
        no_output_timeout: 30m
        name: Check package
        command: R CMD check --no-manual *tar.gz
#    - store_artifacts:
#        path: ci4rB.Rcheck/
#    - save_cache:
#        key: cache-{{ .Environment.CIRCLE_JOB }}
#        paths:
#          - "/usr/local/lib/R/site-libraryX"

jobs:
  release:
    docker:
      - image: rocker/verse:latest
    <<: *steps
  oldrel:
    docker:
      - image: rocker/verse:4.2
    <<: *steps
  devel:
    docker:
      - image: rocker/verse:devel
    <<: *steps

workflows:
  version: 2
  all:
    jobs:
      - release
#      - oldrel
#      - devel
